Repository cyrilgdn/terraform-provider-vault, pull requests merged in 2021-08, with the labels that each got.

#1 fix: handle Token expiration
  util/client.go
Labels: size/M

#2 feat: allow tls_server_name in the provider
  util/client.go
  vault/provider.go
  website/docs/index.html.markdown
Labels: documentation, size/XS

#4 consul: Manage role policy for Consul < 1.4
  vault/resource_consul_secret_backend_role.go
Labels: size/XS
